### ISSUE TITLE
Inaccurate pointing_at Algorithm used - EDIT : suggesting object picking

### ISSUE THREAD

**Issue by appgurueu** [azekillDIABLO/omicron#1]
Take a look at my AGE Java Game Engine or my Lua pointing_at Mod/API to see how it can be done more accurately & with less calculation power.
Basically, a cube consists outta 6 faces, right ?
A 3D ray can be defined as 3 2D rays.
For all of those, we now check - based on difference - collisionpoint with appropriate cube faces.
LMD

**Comment by azekillDIABLO** [comment]
wow that's some hardcore maths you got there. I'll look at that. Not sure to understand exactly what it does :D

**Comment by appgurueu** [comment]
Edit : No thats a bad idea. Wanna hear a better one ? What about OGL Object Picking ? Would require more rendering but would be legendary !

**Comment by appgurueu** [comment]
If you use all RGBA, you can have up to 256^4-1 objects at a time in your scene ! 
If each object was one pixel big in the rendered scene, then : 65535x65535 would be your maximum rendering size....

https://www.google.com/search?client=ubuntu&hs=GVd&channel=fs&ei=7n5wW7reG4ykwQKK9L74CQ&q=sqrt%28256%5E4-1%29&oq=sqrt%28256%5E4-1%29&gs_l=psy-ab.3..0i8i30k1.7688.10180.0.10422.6.6.0.0.0.0.139.602.5j1.6.0....0...1.1.64.psy-ab..0.6.596...0i8i7i30k1.0.KaV8mcnyceo

tho busy with magic-ctf atm : magicctf.github.io
afterwards will continue working on own game engine :) (Java sry, uses jogl, but supports extensions in lua, python, and js !)

**Comment by appgurueu** [comment]
> wow that's some hardcore maths you got there. I'll look at that. Not sure to understand exactly what it does :D

Not hardcore, phew ;D

Ill try to make you an explanatory drawing...

**Comment by appgurueu** [comment]
Drawing : 
![explanation](https://user-images.githubusercontent.com/34514239/44005369-809b260e-9e72-11e8-8a67-f7c9d292fd88.png)

Now imagine that for all directions...

**Comment by azekillDIABLO** [comment]
You were motivated. Do you want I edit the issue?

**Comment by appgurueu** [comment]
hmm ??? so do you use object picking now ?

**Comment by azekillDIABLO** [comment]
I don't really see the point of adding this nor modifying the pointing system. The performance isn't affected at all...

**Comment by azekillDIABLO** [comment]
Should I close this @appgurueu ? I know I'm too lazy to do it and the benefit is really minor for now.

**Comment by appgurueu** [comment]
"I know I'm too lazy to do it and the benefit is really minor for now."
Close, if you want.
But object picking is a good idea when youll later add custom meshes.

**Comment by azekillDIABLO** [comment]
hmm... it can be useful said like this... will see.

**Comment by azekillDIABLO** [comment]
will close for now
