### ISSUE TITLE
Rendering Disscussion - Current topic: transparency with OGL

### ISSUE THREAD

**Issue by appgurueu** [azekillDIABLO/omicron#2]
Title says it all.

**Comment by azekillDIABLO** [comment]
You mean adding half-transparent blocks? It would be fantastic. It's one my obejctives, especially with water.

**Comment by azekillDIABLO** [comment]
How would you think this can be implemented?

**Comment by appgurueu** [comment]
So it's like you got a fragment shader like : 
...
in vec2 texcoords; //They are passed by Vertex Shader
uniform sampler2D texture; //Texture
...
main void
...
vec4 texcolor=texture(texture,texcoords);
if (texcolor.w == 0) { discard; } //Don't render fragment if alpha = 0
...
//Do fragment calculation here

At least in JOGL...

**Comment by azekillDIABLO** [comment]
This is what I was scared of, I will have to learn OGL. 


Also, a question, do you know a way to make the game render half transparent things, like water? It's currently not implemented, and I must admit I Don't know how to do it.

**Comment by appgurueu** [comment]
owww, half transparent things are really bad to render. You have to sort 'em from farthest to newest and render them in that order, plus disable depth testing and so... You need a tutorial for that... leave it as it is atm i'd say...

http://www.opengl-tutorial.org/intermediate-tutorials/tutorial-10-transparency/

**Comment by azekillDIABLO** [comment]
Thanks for the link. I have a small favor to ask you… can you take a look at the code (main.c, rendering.c, chunk.c, maybe others) and tryna find where is the per face optimization system? I can't find it altough I'm searching since a lot of time. If it's too pesky or too long tell me, there's no problem 😃 
Maybe we should rename this thread to *Rendering Disscussion - Current topic: transparency with OGL*

**Comment by appgurueu** [comment]
rename it.

**Comment by appgurueu** [comment]
Problem lays in your fragment shader : gl_FragColor = vec4(color, 1.0); <- No transparency possible

**Comment by azekillDIABLO** [comment]
Problem fully fixed! I should have closed this earlier but I waited to see if all the other bugs were not related (ulgy faces in water). *DONE!*
