### ISSUE TITLE
No license in the repository

### ISSUE THREAD

**Issue by Panquesito7** [azekillDIABLO/omicron#6]

**Comment by LifeCANvs** [comment]
I would also like to know which license applies to this project? Is it also MIT as the original from which you forked it?

**Comment by azekillDIABLO** [comment]
Same as the fork!

**Comment by RodrigueLemaire** [comment]
https://github.com/azekillDIABLO/omicron/commit/a30d5497a2dafddf8a8c7d4342a6261232f82f37

done
